name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        
      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            APPS_SCRIPT_URL
            AUTHORIZED_USERS
            BOT_TOKEN
            SHARED_SECRET
            WEBHOOK_SECRET
        env:
          APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }}
          AUTHORIZED_USERS: ${{ secrets.AUTHORIZED_USERS }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SHARED_SECRET: ${{ secrets.SHARED_SECRET }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
